global:
  scrape_interval:     15s
  evaluation_interval: 15s

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'loki'
    scrape_interval: 15s
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'promtail'
    scrape_interval: 15s
    static_configs:
      - targets: ['promtail:9080']
  
  - job_name: 'all_services'
    scrape_interval: 15s
    static_configs:
      - targets: ['loki:3100', 'promtail:9080', 'grafana:3000', 'prometheus:9090']