apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: moscow-time-app
    meta.helm.sh/release-namespace: default
type: Opaque
data:
  username: YWRtaW4=
  password: YWRtaW5fcGFzc3dvcmQ=
